import type { Profile, Availability, Booking } from './types';

export const MOCK_TUTORS: Profile[] = [
    {
        id: 'tutor-1',
        email: 'sarah.mitchell@example.com',
        full_name: 'Sarah Mitchell',
        role: 'tutor',
        avatar_url: null,
        bio: 'Cambridge-certified English tutor with 8 years of experience. Specialized in IELTS preparation, business English, and conversational fluency. I believe in building confidence through practical, real-world communication.',
        video_intro_url: null,
        created_at: '2024-01-15',
    },
    {
        id: 'tutor-2',
        email: 'james.harrington@example.com',
        full_name: 'James Harrington',
        role: 'tutor',
        avatar_url: null,
        bio: 'Former Oxford lecturer turned private tutor. My approach combines classic literature analysis with modern communication skills. Whether you need academic writing support or presentation coaching, I\'m here to help.',
        video_intro_url: null,
        created_at: '2024-02-20',
    },
    {
        id: 'tutor-3',
        email: 'emma.clarke@example.com',
        full_name: 'Emma Clarke',
        role: 'tutor',
        avatar_url: null,
        bio: 'Native British English speaker with TEFL certification. I specialize in helping intermediate learners break through to advanced fluency. Fun, engaging lessons tailored to your goals.',
        video_intro_url: null,
        created_at: '2024-03-10',
    },
    {
        id: 'tutor-4',
        email: 'david.chen@example.com',
        full_name: 'David Chen',
        role: 'tutor',
        avatar_url: null,
        bio: 'Bilingual English-Mandarin tutor specializing in cross-cultural communication. 5 years of corporate training experience with multinational companies. TOEFL & IELTS prep expert.',
        video_intro_url: null,
        created_at: '2024-03-25',
    },
    {
        id: 'tutor-5',
        email: 'olivia.romano@example.com',
        full_name: 'Olivia Romano',
        role: 'tutor',
        avatar_url: null,
        bio: 'Passionate about making English accessible and enjoyable. MA in Applied Linguistics from UCL. I create personalized lesson plans that adapt to your learning style and pace.',
        video_intro_url: null,
        created_at: '2024-04-05',
    },
    {
        id: 'tutor-6',
        email: 'william.brooks@example.com',
        full_name: 'William Brooks',
        role: 'tutor',
        avatar_url: null,
        bio: 'Professional English tutor and published author. I focus on advanced grammar, creative writing, and public speaking. Let\'s polish your English to perfection.',
        video_intro_url: null,
        created_at: '2024-04-18',
    },
];

export const MOCK_AVAILABILITY: Availability[] = [
    { id: 'av-1', tutor_id: 'tutor-1', day_of_week: 1, start_time: '09:00', end_time: '12:00' },
    { id: 'av-2', tutor_id: 'tutor-1', day_of_week: 1, start_time: '14:00', end_time: '17:00' },
    { id: 'av-3', tutor_id: 'tutor-1', day_of_week: 3, start_time: '10:00', end_time: '15:00' },
    { id: 'av-4', tutor_id: 'tutor-1', day_of_week: 5, start_time: '09:00', end_time: '13:00' },
    { id: 'av-5', tutor_id: 'tutor-2', day_of_week: 2, start_time: '11:00', end_time: '16:00' },
    { id: 'av-6', tutor_id: 'tutor-2', day_of_week: 4, start_time: '13:00', end_time: '18:00' },
    { id: 'av-7', tutor_id: 'tutor-3', day_of_week: 1, start_time: '08:00', end_time: '12:00' },
    { id: 'av-8', tutor_id: 'tutor-3', day_of_week: 2, start_time: '08:00', end_time: '12:00' },
    { id: 'av-9', tutor_id: 'tutor-3', day_of_week: 3, start_time: '14:00', end_time: '19:00' },
    { id: 'av-10', tutor_id: 'tutor-4', day_of_week: 1, start_time: '10:00', end_time: '14:00' },
    { id: 'av-11', tutor_id: 'tutor-4', day_of_week: 3, start_time: '10:00', end_time: '14:00' },
    { id: 'av-12', tutor_id: 'tutor-4', day_of_week: 5, start_time: '10:00', end_time: '14:00' },
    { id: 'av-13', tutor_id: 'tutor-5', day_of_week: 2, start_time: '09:00', end_time: '13:00' },
    { id: 'av-14', tutor_id: 'tutor-5', day_of_week: 4, start_time: '09:00', end_time: '13:00' },
    { id: 'av-15', tutor_id: 'tutor-6', day_of_week: 1, start_time: '15:00', end_time: '20:00' },
    { id: 'av-16', tutor_id: 'tutor-6', day_of_week: 4, start_time: '15:00', end_time: '20:00' },
];

export const MOCK_BOOKINGS: Booking[] = [
    {
        id: 'book-1',
        student_id: 'student-1',
        tutor_id: 'tutor-1',
        booking_date: '2026-02-19',
        start_time: '10:00',
        end_time: '11:00',
        status: 'approved',
        meeting_link: 'https://meet.google.com/abc-defg-hij',
        created_at: '2026-02-17',
    },
    {
        id: 'book-2',
        student_id: 'student-1',
        tutor_id: 'tutor-2',
        booking_date: '2026-02-20',
        start_time: '13:00',
        end_time: '14:00',
        status: 'pending',
        meeting_link: null,
        created_at: '2026-02-17',
    },
    {
        id: 'book-3',
        student_id: 'student-2',
        tutor_id: 'tutor-1',
        booking_date: '2026-02-18',
        start_time: '14:00',
        end_time: '15:00',
        status: 'pending',
        meeting_link: null,
        created_at: '2026-02-16',
    },
];

export const MOCK_STUDENT: Profile = {
    id: 'student-1',
    email: 'john.student@example.com',
    full_name: 'John Doe',
    role: 'student',
    avatar_url: null,
    bio: 'Intermediate English learner looking to improve conversation skills.',
    video_intro_url: null,
    created_at: '2024-05-01',
};
